# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ui test integration

on:
  push:
      branches:
        - '**'
  pull_request:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    name: create sh
    run: sh /.build.sh
    name: Pushes to another repository
      id: OPOII/UITest
      uses: OPOII/UITesty@cp_instead_of_deleting
      env:
        API_TOKEN_GITHUB: ${{ secrets.FRONT_TOKEN }} 
      with:
        source-directory: 'output'
        destination-github-username: 'OPOII'
        destination-repository-name: 'books-ui'
        commit-message: See ORIGIN_COMMIT
      name: Test get variable exported by push-to-another-repository
      run: npm run serve

  cypress-run:

    runs-on: ubuntu-latest
    name: UI-TEST on chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          command: npm run test:e2e:ui:headless

      

      
