# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ui test integration

on:
  push:
      branches:
        - '**'
  pull_request:
    branches: [main]
  repository_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
